- hosts: terraform-ansible
  tasks:
    - name: install python3, virtualenv
      apt: 
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
    - name: install dependencies with pip (Django and Djando Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework
    - name: initialize the project
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
      ignore_errors: yes
    - name: alter hosts from settings 
      lineinfile: 
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
